name: pdm
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

assets:
  - lib/Home/
  - lib/Home/assets/
  - lib/Home/assets/i18n/
  - lib/Home/assets/images/
  - lib/Login/
  - lib/Login/assets/
  - lib/Login/assets/i18n/
  - lib/Login/assets/images/
  - lib/ResetPassaword/
  - lib/ResetPassaword/assets/
  - lib/ResetPassaword/assets/i18n/
  - lib/ResetPassaword/assets/images/
  - lib/Sigup/
  - lib/Sigup/assets/
  - lib/Sigup/assets/i18n/
  - lib/Sigup/assets/images/
