# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vjHs8Z13bO5H91xMk9hXsI_ne_hIV5DX
"""

!pip install pandas

import pandas as pd
import numpy as np
import re

df = pd.read_csv('twitterSlang.csv')

print(df.to_string())

#df1 = pd.read_csv('twitterSlang2.csv', encoding='cp1252')
#print(df1.to_string())

slang = df['slang'].tolist()
translation = df['formal_translation'].tolist()

dataset = [
  'if you guys are bummed abt the owl house hiatus and amphibia ending may i introduce to you dead end paranormal park',
  'people who dont get motion sick how does it feel to be god',
  'Must u guys eat on dates what about going hiking golfing taking walks in scenic areas',
  'Happy bday to Hua Cheng',
  'Sephiroth walking is too weird for me i feel like hed be the type of guy whod levitate everywhere',
  'lmao elizabeth olsen supremacy tho'
]

for idz,z in enumerate(dataset):
  txt = re.sub("[^\w]", " ",  dataset[idz]).split()
  for idx,x in enumerate(txt):
    for idy,y in enumerate(slang):
      if txt[idx] in slang[idy]:
        print('A tradução da gíria {} é {}'.format(slang[idy], translation[idy]))
      else:
        print('Não foram encontradas gírias :o!')

txt = ['people', 'who', 'dont', 'get', 'motion', 'sick', 'how', 'does', 'it', 'feel', 'to', 'be', 'god']
for idx,x in enumerate(txt):
    for idy,y in enumerate(slang):
      if txt[idx] in slang[idy]:
        print('A tradução da gíria {} é {}'.format(slang[idy], translation[idy]))
      else:
        print('Não foram encontradas gírias :o!')

for idz,z in enumerate(dataset):
  txt = re.sub("[^\w]", " ",  dataset[idz]).split()
  print(txt)

from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/')
def hello_world():
    json_file = {}
    json_file['query'] = 'hello_world'
    return jsonify(json_file)
    #return 'Hello World!'

if __name__ == '__main__':
    app.run()

xs = 'bleu bleu'
for idx, x in enumerate(txt):
    print(txt[idx])
    print(len(txt))

import re

txt = 'I think abt you'
wordList = re.sub("[^\w]", " ",  txt).split()
len(wordList)